# QA Test Automation Pipeline for Adobe

trigger:
 branches:
  include:
    - develop
 paths:
  exclude:
    - .azure-pipelines/*
    - readme.md

pool:
  vmImage: 'ubuntu-latest'

parameters:

- name: AEM_BVT
  displayName: Run AEM Build Validation
  type: boolean
  default: false

- name: AEM_Regression
  displayName: Run AEM Regression Suite
  type: boolean
  default: false

- name: SAP_BVT
  displayName: Run SAP Build Validation
  type: boolean
  default: false

- name: SAP_Regression
  displayName: Run SAP Regression Suite
  type: boolean
  default: false

- name: Lighthouse_Execution
  displayName: Run Lighthouse Scanning
  type: boolean
  default: false  

- name: Environment
  displayName: Environment name to run tests
  type: string
  default: D2
  values:
    - D1
    - D2


stages:

  - stage: CI
    jobs:
      - job: CI
        timeoutInMinutes: 0
        displayName: CI
        steps:
        
        #copy lighthouse URLs files to be published
        - task: CopyFiles@2
          displayName: 'Copy lighthouse URL file'
          inputs:
            Contents: |
              $(Pipeline.Workspace)/s/lighthouse_execution_urls.txt
            TargetFolder: '$(Build.StagingDirectory)\Lighthouse'

        - task: PublishPipelineArtifact@1
          displayName: Publish Lighthouse artifact
          inputs:
            targetPath: '$(Build.StagingDirectory)\Lighthouse'
            artifactName: 'Lighthouse'

        # build
        - task: Maven@3
          displayName: Maven build task
          inputs:
            mavenPomFile: ./pom.xml
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            goals: 'package'
            options: '-DoutputDirectory=$(Build.StagingDirectory)'
            
        # move files to appropriate subfolders
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.StagingDirectory)'
            TargetFolder: '$(Build.StagingDirectory)\Adobe'
            Contents: 'Adobe**.jar'
        
        - task: CopyFiles@2
          inputs:
            SourceFolder: $(Build.StagingDirectory)
            TargetFolder: $(Build.StagingDirectory)\Sap
            Contents: 'Sap**.jar'
          
        - task: PublishPipelineArtifact@1
          displayName: Publish Adobe artifact
          inputs:
            targetPath: '$(Build.StagingDirectory)\Adobe'
            artifactName: 'Adobe'
            
        - task: PublishPipelineArtifact@1
          displayName: Publish Sap artifact
          inputs:
            targetPath: '$(Build.StagingDirectory)\Sap'
            artifactName: 'Sap'

        - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          - template: qa_modifiedtests.yml

  - stage: Run_QA_Tests_Suites
    dependsOn: CI
    condition: and( succeeded(), in( 'True', '${{ parameters.AEM_BVT }}', '${{ parameters.AEM_Regression }}', '${{ parameters.SAP_BVT }}', '${{ parameters.SAP_Regression}}', '${{ parameters.Lighthouse_Execution}}' ) )
    jobs:
      - job: Run_SAP_Tests_Suites
        timeoutInMinutes: 0
        displayName: Run SAP Tests Suites
        condition: in('True', '${{ parameters.SAP_BVT }}', '${{ parameters.SAP_Regression }}' )
        variables:
          - name: environment
            value: ${{ parameters.Environment }}
        steps:
          - ${{ if eq(parameters.SAP_BVT, true) }}:
            - template: qa_tests.yml
              parameters:
                items:
                  - projname: Sap
                    pattern: 'Sap_BVT*.jar'
                    reportname: 'SAP BVT Extent Report'
                    testname: 'SAP BVT'
          - ${{ if eq(parameters.SAP_Regression, true) }}:
            - template: qa_tests.yml
              parameters:
                items:
                  - projname: Sap
                    pattern: 'Sap_Regression*.jar'
                    reportname: 'SAP Regression Extent Report'
                    testname: 'SAP Regression'

      - job: Run_AEM_Tests_Suites
        timeoutInMinutes: 0
        displayName: Run AEM Tests Suites
        condition: in('True', '${{ parameters.AEM_BVT }}', '${{ parameters.AEM_Regression }}' )
        variables:
          - name: environment
            value: ${{ parameters.Environment }}
        steps:
          - ${{ if eq(parameters.AEM_BVT, true) }}:
            - template: qa_tests.yml
              parameters:
                items:
                  - projname: Adobe
                    pattern: 'Adobe_BVT*.jar'
                    reportname: 'Adobe BVT Extent Report'
                    testname: 'Adobe BVT'
          - ${{ if eq(parameters.AEM_Regression, true) }}:
            - template: qa_tests.yml
              parameters:
                items:
                  - projname: Adobe
                    pattern: 'Adobe_Regression_Mobile*.jar'
                    reportname: 'Adobe Regression Mobile Extent Report'
                    testname: 'Adobe Regression Mobile'
            - template: qa_tests.yml
              parameters:
                items:
                  - projname: Adobe
                    pattern: 'Adobe_Regression_Web_Runner.jar'
                    reportname: 'Adobe Regression Web Extent Report'
                    testname: 'Adobe Regression Web'
            - template: qa_tests.yml
              parameters:
                items:
                  - projname: Adobe
                    pattern: 'Adobe_Regression_Wide_Screen*.jar'
                    reportname: 'Adobe Regression Wide Screen Extent Report'
                    testname: 'Adobe Regression Wide Screen'
            - template: qa_tests.yml
              parameters:
                items:
                  - projname: Adobe
                    pattern: 'Adobe_Regression_Tablet*.jar'
                    reportname: 'Adobe Regression Tablet Extent Report'
                    testname: 'Adobe Regression Tablet'
            - template: qa_tests.yml
              parameters:
                items:
                  - projname: Adobe
                    pattern: 'Adobe_Regression_Web_Edge*.jar'
                    reportname: 'Adobe Regression Web Edge Extent Report'
                    testname: 'Adobe Regression Web Edge'
            - template: qa_tests.yml
              parameters:
                items:
                  - projname: Adobe
                    pattern: 'Adobe_Regression_Web_firefox*.jar'
                    reportname: 'Adobe Regression Web Firefox Extent Report'
                    testname: 'Adobe Regression Web Firefox'
            - template: qa_tests.yml
              parameters:
                items:
                  - projname: Adobe
                    pattern: 'Adobe_Regression_Web_Safari*.jar'
                    reportname: 'Adobe Regression Web Safari Extent Report'
                    testname: 'Adobe Regression Web Safari'

      - job: Run_Lighthouse_Scanning
        displayName: Run Lighthouse Scanning
        condition: in('True', '${{ parameters.Lighthouse_Execution }}' )
        steps:
          - template: qa_lighthouse.yml
            parameters:
              downloadId: current
              downloadArtifact: Lighthouse
              workingDir: $(Pipeline.Workspace)/Lighthouse
              lightHouseDir: $(Pipeline.Workspace)/Lighthouse/lighthouse
              lightHouseUrls: $(Pipeline.Workspace)/Lighthouse/lighthouse_execution_urls.txt
              lightHouseArtifact: $(Build.ArtifactStagingDirectory)/Lighthouse_Reports/lighthouse-$(Build.BuildId).zip           
