# build_testartifacts
# - builds and publishes test artifacts

parameters:
- name: folderPath
  type: string
  default: ''
  
- name: artifactName
  type: string
  default: ''
  

jobs:
- job: build_${{ parameters.artifactName }}
  displayName: Build ${{ parameters.artifactName }} Test Suite
  condition: succeeded()
  variables:
    filePath: ${{ format('{0}/pom.xml', parameters.folderPath) }}
    artifactName: ${{ parameters.artifactName }}
    outputDirectory: $(Build.StagingDirectory)/${{ parameters.artifactName }}
  steps:
  - script: |
       echo "filePath: $(filePath)"
       echo "artifactName: $(artifactName)"
       echo "outputDirectory: $(outputDirectory)"
    displayName: Display variables
  
  # build 
  - task: Maven@3
    displayName: Maven build task
    inputs:
      mavenPomFile: $(filePath)
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      goals: 'package'
      options: '-DoutputDirectory=$(outputDirectory)'

  # publish build artifact
  - task: PublishPipelineArtifact@1
    displayName: Publish $(artifactName) artifact
    inputs:
      targetPath: '$(outputDirectory)' 
      artifactName: '$(artifactName)'
